/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx}",
    "./src/**/*.{ts,tsx}",
  ],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        blue: {
          50: "var(--colours-blue-50)",
          100: "var(--colours-blue-100)",
          200: "var(--colours-blue-200)",
          300: "var(--colours-blue-300)",
          400: "var(--colours-blue-400)",
          500: "var(--colours-blue-500)",
          600: "var(--colours-blue-600)",
          700: "var(--colours-blue-700)",
          800: "var(--colours-blue-800)",
          900: "var(--colours-blue-900)",
          950: "var(--colours-blue-950)",
        },
        gray: {
          50: "var(--colours-gray-50)",
          100: "var(--colours-gray-100)",
          200: "var(--colours-gray-200)",
          300: "var(--colours-gray-300)",
          400: "var(--colours-gray-400)",
          500: "var(--colours-gray-500)",
          600: "var(--colours-gray-600)",
          700: "var(--colours-gray-700)",
          800: "var(--colours-gray-800)",
          900: "var(--colours-gray-900)",
          950: "var(--colours-gray-950)",
        },
        green: {
          50: "var(--colours-green-50)",
          100: "var(--colours-green-100)",
          200: "var(--colours-green-200)",
          300: "var(--colours-green-300)",
          400: "var(--colours-green-400)",
          500: "var(--colours-green-500)",
          600: "var(--colours-green-600)",
          700: "var(--colours-green-700)",
          800: "var(--colours-green-800)",
          900: "var(--colours-green-900)",
          950: "var(--colours-green-950)",
        },
        orange: {
          50: "var(--colours-orange-50)",
          100: "var(--colours-orange-100)",
          200: "var(--colours-orange-200)",
          300: "var(--colours-orange-300)",
          400: "var(--colours-orange-400)",
          500: "var(--colours-orange-500)",
          600: "var(--colours-orange-600)",
          700: "var(--colours-orange-700)",
          800: "var(--colours-orange-800)",
          900: "var(--colours-orange-900)",
          950: "var(--colours-orange-950)",
        },
        pink: {
          50: "var(--colours-pink-50)",
          100: "var(--colours-pink-100)",
          200: "var(--colours-pink-200)",
          300: "var(--colours-pink-300)",
          400: "var(--colours-pink-400)",
          500: "var(--colours-pink-500)",
          600: "var(--colours-pink-600)",
          700: "var(--colours-pink-700)",
          800: "var(--colours-pink-800)",
          900: "var(--colours-pink-900)",
          950: "var(--colours-pink-950)",
        },
        purple: {
          50: "var(--colours-purple-50)",
          100: "var(--colours-purple-100)",
          200: "var(--colours-purple-200)",
          300: "var(--colours-purple-300)",
          400: "var(--colours-purple-400)",
          500: "var(--colours-purple-500)",
          600: "var(--colours-purple-600)",
          700: "var(--colours-purple-700)",
          800: "var(--colours-purple-800)",
          900: "var(--colours-purple-900)",
          950: "var(--colours-purple-950)",
        },
        red: {
          50: "var(--colours-red-50)",
          100: "var(--colours-red-100)",
          200: "var(--colours-red-200)",
          300: "var(--colours-red-300)",
          400: "var(--colours-red-400)",
          500: "var(--colours-red-500)",
          600: "var(--colours-red-600)",
          700: "var(--colours-red-700)",
          800: "var(--colours-red-800)",
          900: "var(--colours-red-900)",
          950: "var(--colours-red-950)",
        },
        yellow: {
          50: "var(--colours-yellow-50)",
          100: "var(--colours-yellow-100)",
          200: "var(--colours-yellow-200)",
          300: "var(--colours-yellow-300)",
          400: "var(--colours-yellow-400)",
          500: "var(--colours-yellow-500)",
          600: "var(--colours-yellow-600)",
          700: "var(--colours-yellow-700)",
          800: "var(--colours-yellow-800)",
          900: "var(--colours-yellow-900)",
          950: "var(--colours-yellow-950)",
        },
        primary: {
          borderColor: {
            darker: "var(--primary-border-darker)",
            default: "var(--primary-border-default)",
            lighter: "var(--primary-border-lighter)",
            subtle: "var(--primary-border-subtle)",
          },
          surface: {
            darker: "var(--primary-surface-darker)",
            default: "var(--primary-surface-default)",
            lighter: "var(--primary-surface-lighter)",
            subtle: "var(--primary-surface-subtle)",
          },
          text: {
            label: "var(--primary-text-label)",
          },
        },

        accent: {
          borderColor: {
            darker: "var(--accent-border-darker)",
            default: "var(--accent-border-default)",
            lighter: "var(--accent-border-lighter)",
            subtle: "var(--accent-border-subtle)",
          },
          surface: {
            darker: "var(--accent-surface-darker)",
            default: "var(--accent-surface-default)",
            lighter: "var(--accent-surface-lighter)",
            subtle: "var(--accent-surface-subtle)",
          },
          text: {
            label: "var(--accent-text-label)",
          },
        },
        error: {
          borderColor: {
            darker: "var(--error-border-darker)",
            default: "var(--error-border-default)",
            lighter: "var(--error-border-lighter)",
            subtle: "var(--error-border-subtle)",
          },
          surface: {
            darker: "var(--error-surface-darker)",
            default: "var(--error-surface-default)",
            lighter: "var(--error-surface-lighter)",
            subtle: "var(--error-surface-subtle)",
          },
          text: {
            label: "var(--error-text-label)",
          },
        },
        success: {
          borderColor: {
            darker: "var(--success-border-darker)",
            default: "var(--success-border-default)",
            lighter: "var(--success-border-lighter)",
            subtle: "var(--success-border-subtle)",
          },
          surface: {
            darker: "var(--success-surface-darker)",
            default: "var(--success-surface-default)",
            lighter: "var(--success-surface-lighter)",
            subtle: "var(--success-surface-subtle)",
          },
          text: {
            label: "var(--success-text-label)",
          },
        },

        grayscaleBorder: {
          darker: "var(--grayscale-border-darker)",
          default: "var(--grayscale-border-default)",
          disabled: "var(--grayscale-border-disabled)",
        },
        grayscaleSurface: {
          default: "var(--grayscale-surface-default)",
          disabled: "var(--grayscale-surface-disabled)",
          subtle: "var(--grayscale-surface-subtle)",
        },
        grayscaleText: {
          body: "var(--grayscale-text-body)",
          caption: "var(--grayscale-text-caption)",
          disabled: "var(--grayscale-text-disabled)",
          negative: "var(--grayscale-text-negative)",
          subtitle: "var(--grayscale-text-subtitle)",
          title: "var(--grayscale-text-title)",
        },
      },
      borderRadius: {
        xs: "var(--radius-xs)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
      fontSize: {
        h1: "var(--h1-----regular)", // Assuming "regular" is the default size
        "h1-bold": "var(--h1-----bold)",
        "h1-light": "var(--h1-----light)",
        h2: "var(--h2-----regular)",
        "h2-bold": "var(--h2---bold)",
        "h2-light": "var(--h2---light)",
        h3: "var(--h3-----regular)",
        "h3-bold": "var(--h3---bold)",
        "h3-light": "var(--h3-----light)",
        h4: "var(--h4-----regular)",
        "h4-bold": "var(--h4---bold)",
        "h4-light": "var(--h4-----light)",
        headline: "var(--headline-----regular)",
        "headline-bold": "var(--headline-----bold)",
        "headline-light": "var(--headline-----light)",
        body: "var(--body---regular)",
        "body-bold": "var(--body---bold)",
        "body-light": "var(--body-----light)",
        subtitle: "var(--subtitle-----regular)",
        "subtitle-bold": "var(--subtitle---bold)",
        "subtitle-light": "var(--subtitle-----light)",
        caption: "var(--caption-----regular)",
        "caption-bold": "var(--caption-----bold)",
        "caption-light": "var(--caption-----light)",
        footnote: "var(--footnote---regular)",
        "footnote-bold": "var(--footnote---bold)",
        "footnote-light": "var(--footnote---light)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
